---
- hosts: all
  gather_facts: no
  become: yes

  pre_tasks:
    - name: install python if missing
      raw: test -e /usr/bin/python3 || (apt update && apt install -y python3-minimal)
      changed_when: no
    - setup:  # aka gather_facts

  roles:
    - common
    - name: networking
      host_ip: "192.168.1.60"
      ipv6_block: "2a01:cb1d:82cd:fe00::/56"
    - samba
    - transmission
...
