---
- hosts: all
  gather_facts: no
  become: yes

  pre_tasks:
    - name: install python if missing
      raw: test -e /usr/bin/python3 || (apt update && apt install -y python3-minimal)
      changed_when: no
    - setup:  # aka gather_facts

  roles:
    - common
    - dhcpd
    - samba
    - transmission
    - docker
    - pihole
    - plex
...
