---
- hosts: all
  become: yes
  gather_facts: no
  pre_tasks:
    - name: install python if missing
      raw: test -e /usr/bin/python3 || (apt update && apt install -y python3-minimal)
      changed_when: no
    - setup:  # aka gather_facts
  roles:
    - common

- hosts: home
  become: yes
  roles:
    - transmission
    # - samba
    # - homeassistant
    # - nginx

- hosts: dhcp_server
  become: yes
  collections:
    - community.general
  roles:
    - dhcp-server

- hosts: levillage
  become: yes
  collections:
    - community.general
  roles:
    - dhcp-server
...
