---
- hosts: nar-shaddaa
  gather_facts: no
  become: yes

  vars:
    dependencies:
      - libselinux-python
      - policycoreutils-python
      - python-firewall
    storage_location: /mnt/storage

  tasks:
    - include: bootstrap_python2.yml
    - name: gather facts
      setup:
    - name: install dependencies
      dnf:
        name: "{{item}}"
      with_items: "{{dependencies}}"

  roles:
    - samba
...
