---
- name: install samba
  dnf:
    name: samba
- name: create storage location
  file:
    path: "{{storage_location}}"
    state: directory
    owner: "{{local_user}}"
    group: "{{local_user}}"
    mode: 0755
- name: SELinux add file context mapping definition
  sefcontext:
    target: "{{storage_location}}(/.*)?"
    setype: samba_share_t
  register: filecontext
- name: SELinux restore default security context
  command: restorecon -R -v {{storage_location}}
  when: filecontext.changed
- name: install samba configuration
  template:
    src: smb.conf
    dest: /etc/samba/
  notify: restart samba
- name: enable and start services
  service:
    name: "{{item}}"
    enabled: yes
    state: started
  with_items: "{{samba_services}}"
- name: add firewall rules
  firewalld:
    service: samba
    permanent: true
    immediate: yes
    state: enabled
...
