---
- name: install samba
  apt:
    name: samba
- name: create storage location
  file:
    path: "{{storage_location}}"
    state: directory
- name: set {{local_user}} user acl of {{storage_location}}
  acl:
    path: "{{storage_location}}"
    etype: user
    entity: "{{local_user}}"
    permissions: rwX
    state: present
    default: "{{item}}"
  with_items: [yes, no]
- name: set other acl of {{storage_location}}
  acl:
    path: "{{storage_location}}"
    etype: other
    permissions: rwX
    state: present
    default: yes
    recursive: yes
- name: install samba configuration
  template:
    src: smb.conf
    dest: /etc/samba/
  notify: restart samba
- name: enable and start services
  service:
    name: "{{item}}"
    enabled: yes
    state: started
  with_items:
    - smb.service
    - nmb.service

# - name: add firewall rules
#   firewalld:
#     service: samba
#     permanent: true
#     immediate: yes
#     state: enabled
...
