---
- name: install transmission-daemon
  apt:
    name: transmission-daemon
- name: set transmission user acl of {{storage_location}}
  acl:
    path: "{{storage_location}}"
    etype: user
    entity: debian-transmission
    permissions: rwX
    state: present
    default: "{{item}}"
  with_items: [yes, no]
- name: install configuration
  template:
    src: settings.json
    dest: /etc/transmission-daemon/
    owner: debian-transmission
    group: debian-transmission
  notify: restart transmission
- name: enable and start services
  service:
    name: transmission-daemon.service
    enabled: yes
    state: started
...
