---
- name: install transmission-daemon
  apt:
    name: transmission-daemon
- name: Ensure ZFS dataset has support for POSIX ACLs
  community.general.zfs:
    name: "{{item}}"
    state: present
    extra_zfs_properties:
      xattr: on
      aclmode: passthrough
      aclinherit: passthrough
  with_items: "{{zfs_volumes}}"
- name: set transmission user acl of {{storage_location}}
  acl:
    path: "{{storage_location}}"
    etype: user
    entity: debian-transmission
    permissions: rwX
    state: present
    default: "{{item}}"
  with_items: [yes, no]
- name: stop service
  service:
    name: transmission-daemon.service
    state: stopped
- name: install configuration
  template:
    src: settings.json
    dest: /home/thomas/.config/transmission-daemon/
    owner: thomas
    group: thomas
  notify: restart transmission
- name: enable and start service
  service:
    name: transmission-daemon.service
    enabled: yes
    state: started
...
