---
- include: bootstrap_python2.yml
- name: gather facts
  setup:
- name: install dependencies
  dnf:
    name: "{{item}}"
  with_items:
    - htop
    - libselinux-python
    - policycoreutils-python
    - python-firewall
    - tmux
- name: set hostname
  hostname:
    name: "{{hostname}}"
- name: create user
  user:
    name: "{{local_user}}"
    group: "{{local_user}}"
...
