---
- name: gather facts
  setup:
- name: install dependencies
  dnf:
    name: "{{item}}"
  with_items:
    - htop
    - libselinux-python
    - python-firewall
    - tmux
    - tuned  # performance profile management in Cockpit
- name: set hostname
  hostname:
    name: "{{hostname}}"
- name: create user
  user:
    name: "{{local_user}}"
    group: "{{local_user}}"

# Put SELinux in permissive mode, logging actions that would be blocked.
- name: set selinux to permissive
  selinux:
    policy: targeted
    state: permissive
...
