---
- name: install dependencies
  apt:
    name: "{{item}}"
  with_items:
    - acl
    - locales
    - tmux

- name: set hostname
  hostname:
    name: "{{hostname}}"

- name: set timezone to Europe/Paris
  timezone:
    name: Europe/Paris
- name: generate locale
  locale_gen:
    name: en_US.UTF-8
    state: present
- name: set locale
  copy:
    content: |
      LANG=en_US.UTF-8
      LC_ALL=en_US.UTF-8
    dest: "/etc/default/locale"
    owner: root
    group: root
    mode: 0644

- group:
    name: "{{local_user}}"
    state: present
- name: create user
  user:
    name: "{{local_user}}"
    group: "{{local_user}}"

- name: add trim cron
  cron:
    name: "trim"
    minute: "0"
    hour: "5"
    job: "/sbin/fstrim --all || true"
...
