---
- name: add local DNS records
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  loop:
    - '192.168.1.1	livebox.lan'
    - '192.168.1.60	home.maurin.io'
    - '192.168.1.60	pi.hole'
- name: check if volume (pihole-etc) exists
  command: docker volume inspect pihole-etc
  register: result
  ignore_errors: yes
  changed_when: no
- name: create volume (pihole-etc)
  command: docker volume create pihole-etc
  when: result is failed
- name: check if volume (pihole-dnsmasqd) exists
  command: docker volume inspect pihole-dnsmasqd
  register: result
  ignore_errors: yes
  changed_when: no
- name: create volume (pihole-dnsmasqd)
  command: docker volume create pihole-dnsmasqd
  when: result is failed
- name: get IP address
  shell: ip route get 8.8.8.8 | awk '{for(i=1;i<=NF;i++) if ($i=="src") print $(i+1)}'
  register: ip_address
  changed_when: no
- name: get IPv6 address
  shell: ip -6 route get 2001:4860:4860::8888 | awk '{for(i=1;i<=NF;i++) if ($i=="src") print $(i+1)}'
  register: ipv6_address
  changed_when: no
- name: get Timezone
  command: date +%Z
  register: timezone
  changed_when: no
- name: pull Pi-Hole image
  docker_image:
    name: pihole/pihole:latest
    source: pull
    force_source: yes
- name: stop Pi-Hole
  docker_container:
    name: pihole
    state: absent
  ignore_errors: yes
  register: container_stop
  until: not container_stop.get("failed")
  retries: 5
  delay: 10
- name: start Pi-Hole
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    restart_policy: unless-stopped
    dns_servers:
    - "127.0.0.1"
    - "1.1.1.1"
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "80:80/tcp"
    - "443:443/tcp"
    volumes:
    - pihole-etc:/etc/pihole/
    - pihole-dnsmasqd:/etc/dnsmasq.d/
    env:
      ServerIP: "{{ip_address.stdout}}"
      ServerIPv6: "{{ipv6_address.stdout}}"
      TZ: "{{timezone.stdout}}"
      WEBPASSWORD: "{{password}}"
...
